### ISSUE TITLE
Cross-identity reenactment and motion transferring

### ISSUE THREAD

**Issue by yur1xfd** [ShenhanQian/GaussianAvatars#63]
Thank you for the amazing paper and the code release! I have a several questions about cross-identity reenactment:

1. In your paper you demonstrated the results of cross-identity reenactment of head avatars (figure 4) through the [offline rendering](https://github.com/ShenhanQian/GaussianAvatars/blob/main/doc/offline_render.md#cross-identity-reenactment). So, how can I reproduce such results as you demonstrate at the [project page](https://shenhanqian.github.io/gaussian-avatars) with expression transferring from source actor to animated avatar? Should I use the output of the offline rendering as an input of your [VHAP](https://github.com/ShenhanQian/VHAP) preprocessing pipeline and then train Gaussian Avatars on this data?
2. Trying to reproduce the results of motion transferring the first idea, that came in my mind, was just swap the .npz files for two different avatars head. The motion sequence of the first avatar contained 999 timestamps, and the second one contained 1408 timestamps. So when I tried to see the results with [local viewer](https://github.com/ShenhanQian/GaussianAvatars/blob/main/local_viewer.py) using .ply file of first avatar as a --point_path and .npz file of second avatar as a --motion_path I got this error:
` /opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [30,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [30,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [30,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [30,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [30,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/vr/Projects/gaussian-avatars/GaussianAvatars/local_viewer.py", line 685, in <module>
    gui.run()
  File "/home/vr/miniconda3/envs/gaussian-avatars/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vr/Projects/gaussian-avatars/GaussianAvatars/local_viewer.py", line 674, in run
    self.gaussians.select_mesh_by_timestep(self.timestep)
  File "/home/vr/Projects/gaussian-avatars/GaussianAvatars/scene/flame_gaussian_model.py", line 121, in select_mesh_by_timestep
    verts, verts_cano = self.flame_model(
  File "/home/vr/miniconda3/envs/gaussian-avatars/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vr/Projects/gaussian-avatars/GaussianAvatars/flame_model/flame.py", line 522, in forward
    vertices, J, mat_rot = lbs(
  File "/home/vr/Projects/gaussian-avatars/GaussianAvatars/flame_model/lbs.py", line 178, in lbs
    J_transformed, A = batch_rigid_transform(rot_mats, J, parents, dtype=dtype)
  File "/home/vr/Projects/gaussian-avatars/GaussianAvatars/flame_model/lbs.py", line 290, in batch_rigid_transform
    curr_res = torch.matmul(transform_chain[parents[i]], transforms_mat[:, i])
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.`
Have you ever faced it before?

**Comment by ShenhanQian** [comment]
Hi, you don't need to feed the output of GA (GaussianAvatars) to VHAP as input. You just need to:
1. Run VHAP on all subjects relavant, including subject A and B below.
2. Then train GA on subject A for the avatar.
3. Run offline rendering of the trained avatar (subject A) with a motion sequence from subject B.
```shell
SUBJECT=A
TGT_SUBJECT=B

python render.py \
-t data/${TGT_SUBJECT}_FREE_v16_DS2-0.5x_lmkSTAR_teethV3_SMOOTH_offsetS_whiteBg_maskBelowLine \
-m output/UNION10EMOEXP_${SUBJECT}_eval_600k \
--select_camera_id 8  # front view
```
Sorry for the confusion caused by our naming. The "source actor" in our figure indeed corresponds to the "TGT_SUBJECT" in our code, which refers to "a target subject for motion"

**Comment by yur1xfd** [comment]
Thank you! I got it. And what about motion transferring from one avatar to another in the form of a 3D scene? Can I do that simply by swapping the .npz files of corresponding avatars (I show an error raised when I tried to do it)? Or should I do some extra steps?

**Comment by ShenhanQian** [comment]
Sorry, I don't get what you mean by "a 3D scene". 

The error you have shown is "index out of bounds". You can check what parameter(s) has an inconsistency shape before and after the swapping.

**Comment by yur1xfd** [comment]
I'll try explain what I meant. I trained 2 avatars (for example, subjects A and B) on 2 motion sequences (for example, EMO-1 and EMO-2) consist of different frames counts (184 and 158 frames respectively): 
```
python train.py \
-s data/AVATAR_A_EMO-1_v16_DS20.5x_lmkSTAR_teethV3_SMOOTH_offsetS_whiteBg_maskBelowLine\
-m output/EXP_EMO-1_AVATAR_A_eval_600k \
--bind_to_mesh --white_background
```
```
python train.py \
-s data/AVATAR_B_EMO-2_v16_DS20.5x_lmkSTAR_teethV3_SMOOTH_offsetS_whiteBg_maskBelowLine\
-m output/EXP_EMO-2_AVATAR_B_eval_600k \
--bind_to_mesh --white_background
```
Then I got 2 `point_cloud` directories with such structure:
```
|-- point_cloud
     |---- point_cloud.ply
     |---- flame_params.npz
```
So, I tried to transfer motion sequence EMO-2 from avatar B to avatar A just by running `local_viewer.py` with swapped `point_path` and `motion_path` parameters:
``` 
python local_viewer.py --point_path /output/EXP_EMO-2_AVATAR_B_eval_600k/point_cloud/point_cloud.ply --motion_path /output/EXP_EMO-1_AVATAR_A_eval_600k/point_cloud/flame_params.npz
```
And got this [error](https://github.com/ShenhanQian/GaussianAvatars/issues/63#issue-2554806439)
But, I think I've figured out why this error occurs. It raised because by default local viewer use .npz file from a same directory where specified by --point_path .ply file is located (from /output/EXP_EMO-2_AVATAR_B_eval_600k in current situation). But when you specify .npz file with `--motion_path` local viewer use it to determine how many frames are contained in this motion sequence. So, the error raised because of mismatch between the number of frames in really used .npz file and
 .npz file specified by `--motion_path` (158 and 184 frames respectively).

Now I moved .ply file of avatar B and .npz file of avatar A to the same directory (/motion_transfer/AVATARS_AB) and run local viewer:
```
python local_viewer.py --point_path /motion_transfer/AVATARS_AB/point_cloud.ply
```
Sharing the results:

<img width="190" alt="Снимок экрана 2024-09-30 в 17 06 37" src="https://github.com/user-attachments/assets/c579ecb7-0c52-4772-929b-5df8ae456ef2">

It looks like gaussians of avatar B binded to mesh of avatar A. Here is a visualization of the avatar A:
![avatar A](https://github.com/user-attachments/assets/9d67e413-7a02-490e-b85b-1120d8e285b1)

Therefore, I'will formulate my question in some other way. Why I obtained different results by rendering with offline rendering (with `render.py`, as you mentioned in previous [comment](https://github.com/ShenhanQian/GaussianAvatars/issues/63#issuecomment-2381274717)) and with local viewer?

**Comment by ShenhanQian** [comment]
If I'm taking it right, you can already do 
    (a) cross-identity reenactment with offline rendering. 

But you encountered the above error when you tried to do 
    (b) cross-identity reenactment with the local viewer.

First, I would like to highlight that (a) uses the FLAME parameters directly from our tracker, while (b) uses the FLAME parameters fine-tuned with 3D-GS. They should not be exactly the same. Our paper used (a) for simplicity.

Secondly, you should not directly swap the `flame_param.npz` files because they contain parameters not only for poses and expressions but also for shape and static_offset. That's where your weird result comes where.

Now comes the real problem. The local viewer reads `point_cloud.ply` and its paired `flame_param.npz` at the beginning, then overwrites dynamic parameters if `--motion_path` is specified. The overwriting appears to succeed, given that the sizes of tensors do change. However,  we still get errors for additional timesteps due to unknown problems. In the end, I fixed it by constructing a new dictionary for `self.flame_param` instead of overwriting items in the initial one. You can pull the latest commit to validate.

**Comment by yur1xfd** [comment]
Thank you so much for your exhaustive reply! I tried to get shape and static_offset from .nfs file of avatar and substitute corresponding parameters for avatar A. It looks good. With several artifacts and misalignment in area of eyes and mouth, but at least I got such a result that I expect to obtain.
